"""Render docs/releases.md from the GitHub Releases API.

CI tooling only (never imported by the application). Runs in the docs
workflow before `mkdocs build`, and also locally:

    python scripts/docs/gen_releases.py --repo behl1anmol/Noesis

Uses stdlib urllib so behavior is identical locally and in CI with zero
dependencies. Sends `Authorization: Bearer $GITHUB_TOKEN` only when the env
var is set (the repo is public; unauthenticated works locally). Output is a
pure function of the API response — no timestamps — so reruns are
byte-identical and the zero-release output matches the committed
placeholder exactly.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

API_ROOT = "https://api.github.com"

HEADER = """\
# Releases

Every tagged release of Noesis, newest first. This page is regenerated by CI
from the [GitHub releases](https://github.com/{repo}/releases) whenever a
release is published.
"""

EMPTY_STATE = """\
!!! note "No releases yet"
    No releases have been published yet — watch the
    [GitHub releases page](https://github.com/{repo}/releases) for the first
    tagged release. This page updates automatically when one lands.
"""


def fetch_releases(repo: str) -> list[dict[str, Any]]:
    """Fetch all releases for *repo*, following Link-header pagination."""
    releases: list[dict[str, Any]] = []
    url: str | None = f"{API_ROOT}/repos/{repo}/releases?per_page=100"
    while url:
        req = urllib.request.Request(
            url,
            headers={
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
                "User-Agent": "noesis-docs-build",
            },
        )
        token = os.environ.get("GITHUB_TOKEN")
        if token:
            req.add_header("Authorization", f"Bearer {token}")
        with urllib.request.urlopen(req, timeout=30) as resp:
            releases.extend(json.load(resp))
            url = _next_link(resp.headers.get("Link"))
    return releases


def _next_link(link_header: str | None) -> str | None:
    if not link_header:
        return None
    for part in link_header.split(","):
        segments = part.split(";")
        if any(s.strip() == 'rel="next"' for s in segments[1:]):
            return segments[0].strip().strip("<>")
    return None


def render(releases: list[dict[str, Any]], repo: str) -> str:
    """Render the releases page. Pure: same input, byte-identical output."""
    out = [HEADER.format(repo=repo)]
    published = [r for r in releases if not r.get("draft")]
    if not published:
        out.append(EMPTY_STATE.format(repo=repo))
        return "\n".join(out)

    published.sort(key=lambda r: r.get("published_at") or "", reverse=True)
    for rel in published:
        tag = rel.get("tag_name", "")
        name = rel.get("name") or tag
        date = (rel.get("published_at") or "")[:10]
        badge = " *(pre-release)*" if rel.get("prerelease") else ""
        out.append(f"\n## {name}{badge}\n")
        out.append(f"**Tag:** [`{tag}`]({rel.get('html_url', '')}) · **Published:** {date}\n")
        body = (rel.get("body") or "").strip()
        if body:
            out.append(body + "\n")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", required=True, help="OWNER/NAME on github.com")
    parser.add_argument("--out", default="docs/releases.md", type=Path)
    parser.add_argument(
        "--strict-fetch",
        action="store_true",
        help="exit non-zero on network/API failure (CI); default keeps the existing file",
    )
    args = parser.parse_args()

    try:
        releases = fetch_releases(args.repo)
    except (urllib.error.URLError, OSError, json.JSONDecodeError) as exc:
        print(f"gen_releases: fetch failed: {exc}", file=sys.stderr)
        if args.strict_fetch:
            return 1
        print("gen_releases: keeping existing releases page", file=sys.stderr)
        return 0

    content = render(releases, args.repo)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    # Atomic replace so a concurrent mkdocs serve never sees a partial file.
    fd, tmp = tempfile.mkstemp(dir=args.out.parent, suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(content)
    os.replace(tmp, args.out)
    print(f"gen_releases: wrote {args.out} ({len(releases)} release(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
